### ISSUE TITLE
Build instructions / Executable 

### ISSUE THREAD

**Issue by kimamb** [gagax1234/OFP#1]
I could not find any build instructions.

I tried using the instructions in the appveyor.yml file, but it ended up with a recursive error in the SDL library when running cmake. It might be because I am trying to compile it on Linux instead of on Windows.

Any help on the build instructions or a precompiled executable available like with OpenFunscripter?

**Comment by gagax1234** [comment]
This project is not really meant for the public yet (not sure if it ever will be).
Checkout the linux section in this instead:
https://github.com/gagax1234/OFP/blob/main/.github/workflows/cmake_build.yml
Also did you `git submodule update --init --recursive` when you cloned the repository?

**Comment by kimamb** [comment]
Okay, trying now.

The serial communication worked fine in OpenFunscripter, so I hope it works here as well.

From what I gathered this is OpenFunscripter with the scripting stuff taken out.

I'll come with an update once this finishes cloning again.

**Comment by gagax1234** [comment]
> The serial communication worked fine in OpenFunscripter, so I hope it works here as well.

That's great. In that case it should work. 👍 

> From what I gathered this is OpenFunscripter with the scripting stuff taken out.

Yes pretty much. 
There's a stronger focus on being able to do everything using a gamepad, Whirligig support and the biggest thing is the Videobrowser which is using an sqlite database which I'm not happy with.
I want to completely get rid of sqlite as it didn't prove to be as useful as I had initially thought.

**Comment by kimamb** [comment]
I was able to build it, but I had to delete
```
      if(NOT HAVE_XEXT_H)
        message_error("Missing Xext.h, maybe you need to install the libxext-dev package?")
      endif()
```
from `sdlchecks.cmake` since I did have libxext-dev installed, but it wouldn't detect it.

I also had to move the whole folder over to one without spaces in the path since SDL didn't understand those that well.

**Comment by kimamb** [comment]
I must say I am impressed by the application!
I am not able to test it out more than opening it.

Though, there is a bunch of questionmarks everywhere.
![bilde](https://user-images.githubusercontent.com/10121762/108517021-2c2ae880-72c7-11eb-98bd-1acd79b564ef.png)
Maybe I should create an issue for that?

Also, on an unrelated note; is it possible to save changes done to the T-code axes? I always have to invert the L0 axis every startup of OpenFunscripter (the issue is probably in OFP as well).

**Comment by gagax1234** [comment]
The question marks are unknown glyphs because the icon font wasn't found.
You need to create a copy of the data directory next to the OFP executable normally the cmake should have done that for you 🤔.

I never thought of it before but I just updated it so the invert settings gets saved.
Everything else got saved so I saw no reason to not save that aswel.
gagax1234/OpenFunscripter@cb1106cb44bbf88541d617128f3005e7a9fac86d
OFP & OFS share the same code.
This repository just includes OFS as a submodule.

You'll need to `git pull` inside the cloned directory OFP and probably do the `git submodule update --init --recursive` aswell.
Because I think git doesn't automatically update submodules.

**Comment by kimamb** [comment]
> The question marks are unknown glyphs because the icon font wasn't found.
> You need to create a copy of the data directory next to the OFP executable normally the cmake should have done that for you thinking.
I see, I moved the binary without thinking about it. Thanks!

And thanks for the update!
